namespace Sexy
{
	public enum WidgetFlags
	{
		WIDGETFLAGS_UPDATE = 1,
		WIDGETFLAGS_MARK_DIRTY = 2,
		WIDGETFLAGS_DRAW = 4,
		WIDGETFLAGS_CLIP = 8,
		WIDGETFLAGS_ALLOW_MOUSE = 0x10,
		WIDGETFLAGS_ALLOW_FOCUS = 0x20
	}
}
