namespace Lawn
{
	public enum MusicTune
	{
		MUSIC_TUNE_NONE = -1,
		MUSIC_TUNE_DAY_GRASSWALK = 1,
		MUSIC_TUNE_NIGHT_MOONGRAINS = 2,
		MUSIC_TUNE_POOL_WATERYGRAVES = 3,
		MUSIC_TUNE_FOG_RIGORMORMIST = 4,
		MUSIC_TUNE_ROOF_GRAZETHEROOF = 5,
		MUSIC_TUNE_CHOOSE_YOUR_SEEDS = 6,
		MUSIC_TUNE_TITLE_CRAZY_DAVE_MAIN_THEME = 7,
		MUSIC_TUNE_PUZZLE_CEREBRAWL = 8,
		MUSIC_TUNE_MINIGAME_LOONBOON = 9,
		MUSIC_TUNE_CONVEYER = 10,
		MUSIC_TUNE_FINAL_BOSS_BRAINIAC_MANIAC = 11,
		MUSIC_TUNE_ZEN_GARDEN = 12,
		NUM_MUSIC_TUNES = 13
	}
}
