namespace Lawn
{
	public enum MusicFile
	{
		MUSIC_FILE_NONE = -1,
		MUSIC_FILE_MAIN_MUSIC = 1,
		MUSIC_FILE_DRUMS = 2,
		MUSIC_FILE_HIHATS = 3,
		MUSIC_FILE_CREDITS_ZOMBIES_ON_YOUR_LAWN = 4,
		NUM_MUSIC_FILES = 5
	}
}
