namespace Lawn
{
	public enum StoreItem
	{
		STORE_ITEM_PLANT_GATLINGPEA = 0,
		STORE_ITEM_PLANT_TWINSUNFLOWER = 1,
		STORE_ITEM_PLANT_GLOOMSHROOM = 2,
		STORE_ITEM_PLANT_CATTAIL = 3,
		STORE_ITEM_PLANT_WINTERMELON = 4,
		STORE_ITEM_PLANT_GOLD_MAGNET = 5,
		STORE_ITEM_PLANT_SPIKEROCK = 6,
		STORE_ITEM_PLANT_COBCANNON = 7,
		STORE_ITEM_PLANT_IMITATER = 8,
		STORE_ITEM_BONUS_LAWN_MOWER = 9,
		STORE_ITEM_POTTED_MARIGOLD_1 = 10,
		STORE_ITEM_POTTED_MARIGOLD_2 = 11,
		STORE_ITEM_POTTED_MARIGOLD_3 = 12,
		STORE_ITEM_GOLD_WATERINGCAN = 13,
		STORE_ITEM_FERTILIZER = 14,
		STORE_ITEM_BUG_SPRAY = 0xF,
		STORE_ITEM_PHONOGRAPH = 0x10,
		STORE_ITEM_GARDENING_GLOVE = 17,
		STORE_ITEM_MUSHROOM_GARDEN = 18,
		STORE_ITEM_WHEEL_BARROW = 19,
		STORE_ITEM_STINKY_THE_SNAIL = 20,
		STORE_ITEM_PACKET_UPGRADE = 21,
		STORE_ITEM_POOL_CLEANER = 22,
		STORE_ITEM_ROOF_CLEANER = 23,
		STORE_ITEM_RAKE = 24,
		STORE_ITEM_AQUARIUM_GARDEN = 25,
		STORE_ITEM_CHOCOLATE = 26,
		STORE_ITEM_TREE_OF_WISDOM = 27,
		STORE_ITEM_TREE_FOOD = 28,
		STORE_ITEM_FIRSTAID = 29,
		STORE_ITEM_INVALID = -1
	}
}
